# Generated by Django 4.2.4 on 2024-03-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoriaproducto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
