# Generated by Django 5.0.2 on 2024-03-07 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='laboral',
            field=models.TextField(default=django.utils.timezone.now, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
