# Generated by Django 5.0.2 on 2024-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_de_trabajo', '0002_trabajador_apellido_trabajador_laboral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='atendidas',
            field=models.BooleanField(default=False),
        ),
    ]
