# Generated by Django 4.2.4 on 2024-03-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_de_trabajo', '0003_trabajador_atendidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
    ]
