# Generated by Django 5.0.2 on 2024-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('targeta', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=8)),
                ('producto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
