# Generated by Django 4.2.4 on 2024-03-22 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
