# Generated by Django 4.2.4 on 2024-03-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante_App', '0002_comprobante_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes'},
        ),
    ]
